name: Update Epaper Links Daily

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 8:30 AM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run scraper
      run: python epaper_scraper.py

    - name: Commit and push if changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add epaper_links.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto update epaper links"
        git push
